### PR TITLE
Add settings menu and review mode.

### PR DESCRIPTION
**Pull request by beersonthewall**
### Summary
Issue #9: added a review mode and settings menu to the report template.

This doesn't have to be the final implementation. Can use this PR to discuss any alternative approaches we may want to go with. As it stands currently the review mode is very basic.

open-review-mode
strikethrough
closed

### CODE REVIEW

**Comment by TobiTenno** [comment]
could you ditch the `-` in the scenario while the check is present?
and, if possible, add the checks inside the scenario area so the background stays consistent?

**Comment by beersonthewall** [comment]
Checks inside the scenario button did all sorts of wonky stuff to the formatting of the side nav. I can change the background color of the box it's in to match though. I'll see what I can do about the '-' as well. I wonder if it would look better if we used a bullet point?

**Comment by beersonthewall** [comment]
Changed the background color. Went ahead and changed the '-' to a bullet point. If you still think it looks bad then I can add some code to remove it in review mode.
bg-color-fix

**Comment by jkuester** [comment]
I think I like the bullet point better than the dash either way.

**Comment by jkuester** [comment]
When all of the scenarios in a feature are marked as reviewed, would it make sense to automatically strike-through the feature button as well?

**Comment by beersonthewall** [comment]
That could be helpful given that you can only have one feature open at a time and selecting a new feature automatically closes the previous feature.

**Comment by jkuester** [comment]
So, @beersonthewall and I have been discussing this a bit offline.  Basically, the question has been raised regarding if we should just move this functionality into the desktop app since it seems likely that future more advanced review features will have to be built in the app (https://github.com/cerner/cucumber-forge-desktop/issues/19).  

Putting the review functionality into CFD would also mean that we would not be including the review code in each HTML report.  Additionally, with the review functionality in the app, we can take advantage of actual libraries instead of everything being raw js.

Thoughts?

**Comment by TobiTenno** [comment]
I think it makes more sense to centralize the review functionality to the app and incorporate more into that as an application, and we can be more flexible with styling, content, dependencies, etc, whereas the report itself is meant to be very minimal.

**Comment by beersonthewall** [comment]
Based on a lot of the discussion I'm going to go ahead and close this PR. I'll open a new issue over on the cucumber-forge-desktop and work on porting the review mode.

**Pull request closed without merging**
